apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNetworkingPorts
metadata:
  name: host-network
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces:
    - external-secrets
    - cosign-system
    - gatekeeper-system
    - argocd
    - kube-system
    - argocd-rollouts
    - demo
    - gatekeeper
  parameters:
    hostNetwork: false