apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: run-as-user
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot