apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-library
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # sau controller, trước constraints
spec:
  project: default
  source:
    repoURL: https://github.com/open-policy-agent/gatekeeper-library
    targetRevision: master
    path: gatekeeper/library   # chứa các ConstraintTemplate phổ biến
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true