apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Template cho K8sDisallowedTags (ban latest)
- https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/disallowedtags/template.yaml

# Template cho K8sContainerLimits (require limits)
- https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/containerlimits/template.yaml

# Template cho K8sPSPAllowedUsers (ban root)
- https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/users/template.yaml

# Template cho K8sPSPHostNetworkingPorts (ban hostNetwork)
- https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/host-network-ports/template.yaml